#!/usr/bin/python3

import sys #to read command line arguments
import json

def help_msg():
    print("Wrong option")
    print("Usage:./cmdman -[als] argument")
    print("Examples:")
    print('./cmdman -a "command:description"')
    print('./cmdman -l')
    print('./cmdman -s "ip"')

try:
    if sys.argv[1] == "-a":
        lst=sys.argv[2].split(":")    
        with open("cmd.json","r") as fd:
            data = fd.read()
            if data and data is not None:
                data = json.loads(data)
            else:
                data = []
            with open("cmd.json","w") as fdw:
                    data.append(lst)
                    fdw.write(json.dumps(data))
    elif sys.argv[1] == "-l":
        with open("cmd.json","r") as fd:
            data = fd.read()
            if data:
                for i in json.loads(data):
                    print(f"{i[0]} : {i[1].strip()}")
            else:
                print("No Info")
    elif sys.argv[1] == "-s":
        with open("cmd.json","r") as fd:
            data = fd.read()
            if data:
                for i in json.loads(data):
                    temp=list(filter(lambda x: x.lower() in i[1].lower() , sys.argv[2].split(" ")))
                    if temp:
                        print(f"{i[0]} : {i[1]}")
                    else:
                        continue
    else:
        help_msg()
except:
    help_msg()
